# СЛУЧАЙНЫЕ ЧИСЛА В NUMPY
Для генерации псевдослучайных чисел в NumPy существует подмодуль random.
Самой «базовой» функцией в нём можно считать функцию rand. По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно):

In [3]:
import numpy as np
np.random.rand()

0.08530891463914925

In [4]:
# получим массив из пяти случайных чисел:
np.random.rand(5)

array([0.44438583, 0.527676  , 0.10997837, 0.08669871, 0.68553981])

In [5]:
# Массив из двух случайных строк и трёх столбцов:
np.random.rand(2,3)

array([[0.96332397, 0.5643334 , 0.41510096],
       [0.46212734, 0.49106701, 0.16150258]])

In [ ]:
# Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1, которая принимает в качестве аргумента именно кортеж без распаковки. 
# Она называется sample:
shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],
#       [0.82195372, 0.26435273, 0.00957881]])

Возможно, именно функция sample покажется вам удобнее, поскольку информацию о форме массива обычно удобнее хранить в коде в виде кортежа и не задумываться потом о его распаковке. В остальном функция sample не отличается от rand.

Не всегда требуются числа в диапазоне именно от 0 до 1. На самом деле с помощью специальных формул можно из диапазона от 0 до 1 получить любой другой желаемый диапазон, однако это не требуется делать самостоятельно — в NumPy доступна функция uniform:

In [39]:
# Первые два аргумента — нижняя и верхняя границы диапазона в формате float, 
# третий опциональный аргумент — форма массива (если не задан, возвращается одно число). 
# Форма массива задаётся кортежем или одним числом.
# uniform(low=0.0, high=1.0, size=None)

np.random.uniform(-30, 50)

np.random.uniform(0.5, 0.75, size=5)
# array([0.58078945, 0.58860342, 0.73790553, 0.63448265, 0.70920297])

array([0.73668679, 0.73371813, 0.67466241, 0.63892496, 0.53627477])

In [10]:
# Получим массив из двух строк и трёх столбцов из чисел в интервале от -1000 до 500:
np.random.uniform(-1000, 500, size=(2, 3))
# array([[ 129.22164163,   77.69090611, -132.9656972 ],
#        [  18.65802226, -317.14793906,   85.3613547 ]])

array([[ 205.34432271, -516.21994854,  309.76321368],
       [-206.0865194 , -407.04611068, -959.18759953]])

### ГЕНЕРАЦИЯ INT
Не всегда требуется генерировать числа с плавающей точкой. Иногда бывает удобно получить целые числа int (например, для поля игры в лото). Для генерации целых чисел используется функция random.randint:

#### randint(low, high=None, size=None, dtype=int)

Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.
- Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
- Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
- size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
- dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.

In [12]:
# Сгенерируем таблицу 2x3 от 0 до 3 включительно:
np.random.randint(4,size=(2,3))


array([[1, 2, 1],
       [0, 3, 2]])

In [13]:
# Чтобы задать и нижнюю, и верхнюю границы самостоятельно, передадим два числа, а затем форму:
np.random.randint(6, 12, size=(3,3))

array([[11, 11, 11],
       [ 7,  8, 11],
       [ 7, 11,  6]])

### ГЕНЕРАЦИЯ ВЫБОРОК
Случайные числа можно использовать и для работы с уже существующими данными. Иногда для проверки гипотез о данных бывает удобно перемешать значения, чтобы проверить, является ли наблюдаемая закономерность случайной.

In [14]:
# Возьмём массив из целых чисел от 0 до 5 и перемешаем его:
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])
# Функция random.shuffle перемешивает тот массив, к которому применяется, и возвращает None.

[0 1 2 3 4 5]
None


array([0, 2, 4, 1, 5, 3])

In [19]:
# Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. 
# Она принимает на вход один аргумент — или массив целиком, или одно число:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
print(playlist)
# Обратите внимание, что необязательно передавать в функцию сразу массив: 
# в этот раз мы передали в качестве аргумента список и ошибки не возникло. 
# При этом на выходе получился уже NumPy-массив (это заметно по отсутствию запятых при печати массива). 
# Сам список playlist при этом остался без изменений.

['ACDC' 'The Beatles' 'Deep Purple' 'Pink Floyd']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [20]:
# Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), 
# где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.
np.random.permutation(10)


array([6, 4, 3, 2, 8, 0, 7, 9, 1, 5])

#### Чтобы получить случайный набор объектов из массива, используется функция random.choice:
choice(a, size=None, replace=True)
- a — одномерный массив или число для генерации arange(a);
- size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
- replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

In [32]:
# Выберем случайным образом из списка двоих человек, которые должны будут выступить с отчётом на этой неделе. 
# Для этого из списка имён (опять же, можно передавать в функцию choice не NumPy-массив, а список) получим 
# два случайных объекта без повторений (логично, что нужно выбрать двух разных людей). 
# Сделать это можно вот так:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
np.random.choice(workers, size=2, replace=False)

array(['Maria', 'Ivan'], dtype='<U6')

In [37]:
# Если попытаться получить без повторений массив большего размера, чем имеется объектов в исходном, возникнет ошибка:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
np.random.choice(workers, size=10, replace=False)
# Если разрешить повторения, то ошибки не будет
np.random.choice(workers, size=10, replace=True)

array(['Nikita', 'John', 'John', 'John', 'Maria', 'Maria', 'John', 'Kate',
       'John', 'Kate'], dtype='<U6')

In [38]:
# Например, получим случайную последовательность, которая образуется в результате десяти подбрасываний игральной кости:
np.random.choice(range(1,7), size=10)

array([1, 1, 6, 3, 4, 5, 6, 4, 6, 1])

In [95]:
import numpy as np

np.random.seed(2021)
# В simple сохраните случайное число в диапазоне от 0 до 1
simple = np.random.rand()
print(simple)
# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их в переменную randoms
randoms = np.random.uniform(-150,2021,size=120)
print(randoms)
# Получите массив из случайных целых чисел от 1 до 100 (включительно) из 3 строк и 2 столбцов. Сохраните результат в table
table = np.random.randint(1,101,size=(3,2))
print(table)
# В переменную even сохраните четные числа от 2 до 16 (включительно)
even = np.arange(2,17,2)
print(even)
# Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив изменился
mix = even.copy()
np.random.shuffle(mix)
print(mix)
# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even,size=3,replace=False)
print(select)
# Получите переменную triplet, которая должна содержать перемешанные значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)
print(triplet)

0.3240081590363709
[ 633.17674321  986.24103213  373.10470337 1192.5866625  1124.35448223
  989.33074336  765.20299286  950.87708042    6.22658124 1959.73333853
 1777.14520024 1792.11311146  801.57718096 1180.462889   1455.88233489
  165.62613649  956.25073815 2019.68193405  439.73745563 1452.12802287
  938.10246943  416.75201349  279.77190801  146.33364074 1389.01448221
  923.97823873  920.42942812   16.52768434  480.01371282 1410.10378714
   47.14487586 1845.50861017 1829.04971999  814.97741459 1026.90478994
  354.71314163 1247.75238652  741.301238    368.52027196 1812.00623184
 1211.29218426  441.39211901  849.22826048  353.81416941 -109.81280348
 1051.51569077 1959.80241947  806.97178074 1860.01006887   52.6009598
  722.0148155   -53.90983671 1111.49385586  894.87018653  652.68440019
 1140.99735309 1748.57805318 1287.67568348 1369.54241974 1232.48050695
  100.255509   1767.94240014 1728.68773721 1328.23425383 1818.27254173
  711.5484247   486.79243679 1135.78142773  465.92677156 14

In [174]:
a = 8
chess = np.zeros(shape=(a,a))
chess[::2,1::2] = 1
chess[1::2,::2] = 1
chess


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])